const pets = [
  {
    pet: 'cats',
    pets: [
      {
        id: '1',
        name: 'Hera',
        image: require('../assets/cat1/1a.png'),
        type: 'Mèo ta',
        age: '1 năm tuổi',
        gender: 'gender-female',
        description:
          'bé bị tai nạn và vứt ngoài ngõ kim Ngưu, 2 chân sau hơi yếu nhưng vẫn đi lại được',
        gallery: [
          require('../assets/cat1/1b.jpeg'),
          require('../assets/cat1/1c.jpeg'),
        ],
      },
      {
        id: '2',
        description: 'Bé đi lang thang và bị bỏ, một mắt đục và chân hơi yếu',
        name: 'Dừa',
        image: require('../assets/cat2/1a.png'),
        type: 'Mèo ta',
        age: '3 tháng tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/cat1/1b.jpeg'),
          require('../assets/cat1/1c.jpeg'),
        ],
      },
      {
        id: '3',
        description: 'Mèo hoang trên mái nhà ở An Dương',
        name: 'Chiba',
        image: require('../assets/cat3/1a.png'),
        type: 'Mèo ta',
        age: '1 tháng tuổi',
        gender: 'gender-female',
        gallery: [
          require('../assets/cat1/1b.jpeg'),
          require('../assets/cat1/1c.jpeg'),
        ],
      },
      {
        id: '4',
        description: 'Con của mèo mẹ hoang Misa',
        name: 'Olive',
        image: require('../assets/cat4/1a.png'),
        type: 'Mèo ta',
        age: '3 tháng tuổi',
        gender: 'gender-female',
        gallery: [
          require('../assets/cat1/1b.jpeg'),
          require('../assets/cat1/1c.jpeg'),
        ],
      },
      {
        id: '5',
        description: 'Bé đi lang thang bới rác ở chợ Hoa',
        name: 'Charlot',
        image: require('../assets/cat5/1a.png'),
        type: 'Mèo ta',
        age: '3 tháng tuổi',
        gender: 'gender-female',
        gallery: [
          require('../assets/cat1/1b.jpeg'),
          require('../assets/cat1/1c.jpeg'),
        ],
      },
      {
        id: '6',
        description: 'Bé bị ngã từ tên cao và liệt 2 chân sau',
        name: 'Xoài',
        image: require('../assets/cat6/1a.png'),
        type: 'Mèo ta',
        age: '2 năm tuổi',
        gender: 'gender-female',
        gallery: [
          require('../assets/cat1/1b.jpeg'),
          require('../assets/cat1/1c.jpeg'),
        ],
      },
      {
        id: '7',
        description: 'Bé là mèo hoang, nhóm cứu được cùng 1 bé miu con',
        name: 'Xoài',
        image: require('../assets/cat7/1a.png'),
        type: 'Mèo ta',
        age: '2 năm tuổi',
        gender: 'gender-female',
        gallery: [require('../assets/cat1/1c.jpeg')],
      },
    ],
  },
  {
    pet: 'dogs',
    pets: [
      {
        id: '1',
        description: 'Bị bán thịt',
        name: 'Bắp',
        image: require('../assets/dog1/1a.png'),
        type: ' Chó lai',
        age: '2 năm tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
      {
        id: '2',
        description: 'Bị bán thịt',
        name: 'Chocolate',
        image: require('../assets/dog2/1a.png'),
        type: 'Poodle',
        age: '4 tháng tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
      {
        id: '3',
        description: 'Bị bán thịt',
        name: 'Nâu',
        image: require('../assets/dog3/1a.png'),
        type: 'Chó lai',
        age: '5 năm tuổi',
        gender: 'gender-female',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
      {
        id: '4',
        description: 'Bị bán thịt',
        name: 'Ting Ting',
        image: require('../assets/dog4/1a.png'),
        type: 'Chó ta',
        age: '3 năm tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
      {
        id: '5',
        description: 'Bị bán thịt',
        name: 'Lucky',
        image: require('../assets/dog5/1a.png'),
        type: 'Chó ta',
        age: '3 năm tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
      {
        id: '6',
        description: 'Bị bán thịt',
        name: 'Milo',
        image: require('../assets/dog6/1a.png'),
        type: 'Chó lai',
        age: '2 năm tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
      {
        id: '7',
        description: 'Bị bán thịt',
        name: 'Mimi',
        image: require('../assets/dog7/1a.png'),
        type: 'Chó ta',
        age: '2 năm tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
      {
        id: '8',
        description: 'Bị bán thịt',
        name: 'Nâu',
        image: require('../assets/dog8/1a.png'),
        type: 'Chó ta',
        age: '1 năm tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
      {
        id: '9',
        description: 'Bị bán thịt',
        name: 'Ô liu',
        image: require('../assets/dog9/1a.png'),
        type: 'Chó ta',
        age: '1 năm tuổi',
        gender: 'gender-male',
        gallery: [
          require('../assets/dog1/1b.jpeg'),
          require('../assets/dog1/1c.jpeg'),
          require('../assets/dog1/1d.jpeg'),
        ],
      },
    ],
  },
];

export default pets;
